@startuml

abstract class TreeNode
abstract class Expression
abstract class QueryPlan
abstract class LogicalPlan
abstract class BinaryNode
abstract class UnaryNode
abstract class LeafNode
abstract class SparkPlan
interface BinaryExecNode
interface UnaryExecNode
interface LeafExecNode

TreeNode <|-- Expression
TreeNode <|-- QueryPlan
QueryPlan <|-- LogicalPlan
LogicalPlan <|-- BinaryNode
LogicalPlan <|-- UnaryNode
LogicalPlan <|-- LeafNode
QueryPlan <|-- SparkPlan
SparkPlan <|-- BinaryExecNode
SparkPlan <|-- UnaryExecNode
SparkPlan <|-- LeafExecNode



interface ParserInterface{
parsePlan(sqlText: String): LogicalPlan
}
abstract class AbstractSqlParser

ParserInterface <|-- AbstractSqlParser
AbstractSqlParser <|-- SparkSqlParser



class ArrayList {
Object[] elementData
size()
}

@enduml